package id.my.shelter.app.feature.auth

import android.content.Context
import androidx.credentials.CredentialManager
import androidx.credentials.CustomCredential
import androidx.credentials.GetCredentialRequest
import com.google.android.libraries.identity.googleid.GetGoogleIdOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import id.my.shelter.app.R

/**
 * Launches the system Credential Manager UI (One Tap-style account picker) and returns a Google
 * ID token on success. `default_web_client_id` is auto-generated by the google-services Gradle
 * plugin from google-services.json's Web SDK OAuth client -- nothing to hardcode here.
 *
 * Throws on cancellation or failure; callers should catch androidx.credentials.exceptions.GetCredentialException.
 */
suspend fun requestGoogleIdToken(context: Context): String {
    val credentialManager = CredentialManager.create(context)
    val googleIdOption = GetGoogleIdOption.Builder()
        .setFilterByAuthorizedAccounts(false)
        .setServerClientId(context.getString(R.string.default_web_client_id))
        .build()
    val request = GetCredentialRequest.Builder()
        .addCredentialOption(googleIdOption)
        .build()

    val credential = credentialManager.getCredential(context, request).credential
    check(credential is CustomCredential && credential.type == GoogleIdTokenCredential.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL) {
        "Unexpected credential type from Credential Manager: ${credential.type}"
    }
    return GoogleIdTokenCredential.createFrom(credential.data).idToken
}
